#!/bin/sh

#clock=$(date '+%I')

#case "$clock" in
    #"00") icon="" ;;
    #"01") icon="" ;;
    #"02") icon="" ;;
    #"03") icon="" ;;
    #"04") icon="" ;;
    #"05") icon="" ;;
    #"06") icon="" ;;
    #"07") icon="" ;;
    #"08") icon="" ;;
    #"09") icon="" ;;
    #"10") icon="" ;;
    #"11") icon="" ;;
    #"12") icon="" ;;
#esac

send_notification() {
	TODAY=$(date '+%-d')
	HEAD=$(cal "$1" | head -n1)
	BODY=$(cal "$1" | tail -n7 | sed -z "s|$TODAY|<u><b>$TODAY</b></u>|1")
	FOOT="\n<i>       ~ calendar</i> 󰸗 "
	dunstify -h string:x-canonical-private-synchronous:calendar \
		"$HEAD" "$BODY$FOOT" -u NORMAL
}

case $BUTTON in
    1) send_notification "+0months";;
    3) notify-send "📅 Time/date module" "\- Left click to show show the month via \`cal\`" ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

echo $(date "+ %H:%M:%S | %d.%m w%V")
