#!/bin/sh

case $BUTTON in
    1) setsid -f "$TERMINAL" -e htop ;;
    3) notify-send "🌡️ Temperature module
- Shows CPU temperature in °C
- Left click to open 'htop'" ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

temp=$(sensors -j | jq '."coretemp-isa-0000"."Package id 0"."temp1_input"')
echo " "${temp%\.*}°C
