#!/bin/sh

# Prints the current volume or 🔇 if muted.

case $BUTTON in
    1) pamixer -t ;;
    3) setsid "$TERMINAL" -e pavucontrol & ;;
    6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

[ $(pamixer --get-mute) = true ] && echo 󰸈 && exit

vol="$(pamixer --get-volume)"

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon="󰖀"
else
	icon="󱄠"
fi

echo " $icon $vol%"
