#!/bin/sh


case $BLOCK_BUTTON in
	1) notify-send "This Month" "$(cal -m --color=always)" && notify-send "Appointments" "$(calcurse -d3)" ;;
	3) setsid "$TERMINAL" -e calcurse & ;;
	2) notify-send " Time/date module" "\- Left click to show upcoming appointments for the next three days via \`calcurse -d3\` and show the month via \`cal\`
- Right click opens calcurse if installed" ;;
	6) "$TERMINAL" -e "$EDITOR" "$0" ;;
esac

cdate="$(date '+%d/%m/%y %H:%M (%V)')"
#icon=''

printf "  $cdate"
